[workspace]
members = [
    "crates/hyprcube",
    "crates/hyprcube-core",
    "crates/hyprcube-panels",
    "crates/hyprcube-hyprconf",
]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"
rust-version = "1.85"
authors = ["Mara Vexa"]
license = "MIT"
repository = "https://github.com/maravexa/hyprcube"
readme = "README.md"

[workspace.dependencies]
# Wayland / Smithay
smithay-client-toolkit = "0.19"
wayland-client = "0.31"

# Rendering
tiny-skia = "0.11"
cosmic-text = "0.12"

# Async
tokio = { version = "1", features = ["full"] }
tokio-util = { version = "0.7", features = ["codec"] }

# Serialization / Config
toml = "0.8"
serde = { version = "1", features = ["derive"] }
serde_json = "1"

# Logging
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

# Error handling
thiserror = "2"

# Image / Icons
image = { version = "0.25", default-features = false, features = ["png", "jpeg", "webp", "ico"] }
freedesktop-icons = "0.2"

# Internal crates
hyprcube-core = { version = "0.1.0", path = "crates/hyprcube-core" }
hyprcube-panels = { version = "0.1.0", path = "crates/hyprcube-panels" }
hyprcube-hyprconf = { version = "0.1.0", path = "crates/hyprcube-hyprconf" }
