[package]
name = "hyprcube-panels"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
readme.workspace = true
description = "Settings panels and form models for HyprCube"

[dependencies]
hyprcube-core = { workspace = true }
hyprcube-hyprconf = { workspace = true }
tiny-skia = { workspace = true }
thiserror = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
toml = { workspace = true }
tracing = { workspace = true }
image = { workspace = true }
